# Создаем ServerAccount bob (указываю так же namespace)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
---
# Выдаем ServerAccount bob роль admin в рамках всего кластера
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
# Создаем ServerAccount dave (указываю так же namespace)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: default
