notary:
  enabled: False
expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: harbor.34.71.255.37.xip.io
    controller: default
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      certmanager.k8s.io/acme-challenge-type: http01