apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailabe: 1
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: azorinmsu/paymentservice:v.0.0.2
